import type { Category, Session, ScheduleBlock, RerouteOption, AgentActivityItem, JourneyLogEntry } from './types';

export const categories: Category[] = [
  { id: 'agentic-ai', name: 'Agentic AI', emoji: '🤖', progress: 100 },
  { id: 'genai', name: 'Generative AI', emoji: '🧠', progress: 90 },
  { id: 'architecture', name: 'Architecture', emoji: '🏗️', progress: 80 },
  { id: 'security', name: 'Security', emoji: '🔐', progress: 60 },
  { id: 'observability', name: 'Observability', emoji: '👁️', progress: 30 },
  { id: 'cost', name: 'Cost Optimization', emoji: '💰', progress: 20 },
];

export const sessions: Session[] = [
  {
    id: 'ses-1001',
    title: 'Building Production-Grade Agentic Workflows',
    category: 'Agentic AI',
    level: 300,
    format: 'Workshop',
    venue: 'Venetian',
    room: 'Level 3, Room L3',
    start: '09:00',
    end: '11:00',
    day: 'MON NOV 30',
    match: 94,
    reason: 'Matches your goal to become production-ready with AI agents, and closes your top skill gap in orchestration.',
    speakers: ['Priya Nandakumar, Principal SA'],
    description: 'A hands-on workshop covering agent orchestration, tool use, and production deployment patterns on AWS.',
    locationVerified: true,
  },
  {
    id: 'ses-1002',
    title: 'Threat Modeling for Autonomous AI Agents',
    category: 'Security',
    level: 300,
    format: 'Chalk Talk',
    venue: 'Mandalay Bay',
    room: 'Palm Ballroom',
    start: '11:00',
    end: '12:00',
    day: 'MON NOV 30',
    match: 81,
    reason: 'Closes a gap in your security coverage related to agent permission boundaries.',
    locationVerified: true,
  },
  {
    id: 'ses-1003',
    title: 'Observability for Multi-Agent Systems',
    category: 'Observability',
    level: 300,
    format: 'Breakout',
    venue: 'Caesars Forum',
    room: 'Room 3',
    start: '13:50',
    end: '14:50',
    day: 'MON NOV 30',
    match: 88,
    reason: 'Your production observability path is incomplete — this is the highest-impact session to close it.',
    locationVerified: true,
  },
  {
    id: 'ses-1004',
    title: 'Cost-Aware Architecture for Generative AI',
    category: 'Cost Optimization',
    level: 200,
    format: 'Code Talk',
    venue: 'Venetian',
    room: 'Level 2, Room L8',
    start: '15:30',
    end: '16:30',
    day: 'MON NOV 30',
    match: 72,
    reason: 'Lowest-coverage category; this session is a foundational entry point.',
    locationVerified: false,
  },
  {
    id: 'ses-1005',
    title: 'Deep Dive: Multi-Agent Orchestration Patterns',
    category: 'Agentic AI',
    level: 400,
    format: 'Breakout',
    venue: 'Wynn',
    room: 'Lafite 3',
    start: '09:30',
    end: '10:30',
    day: 'TUE DEC 1',
    match: 91,
    reason: 'Advanced follow-on to Monday\u2019s workshop, recommended once foundational content is complete.',
    locationVerified: true,
  },
  {
    id: 'ses-1006',
    title: 'Generative AI on AWS: Foundations to Fine-Tuning',
    category: 'Generative AI',
    level: 200,
    format: 'Workshop',
    venue: 'Venetian',
    room: 'Level 3, Room L1',
    start: '11:00',
    end: '13:00',
    day: 'TUE DEC 1',
    match: 78,
    reason: 'Rounds out your Generative AI coverage ahead of certification prep.',
    locationVerified: true,
  },
];

export const todayScheduleBlocks: ScheduleBlock[] = [
  { type: 'break', time: '08:30', label: '☕ Breakfast' },
  { type: 'session', time: '09:00', session: sessions[0] },
  { type: 'transition', time: '11:00', durationMin: 12, transitionRisk: 'go', label: '🚶 12 min transition to Mandalay Bay' },
  { type: 'session', time: '11:00', session: sessions[1] },
  { type: 'break', time: '12:00', label: '🍴 Lunch / Recovery' },
  { type: 'transition', time: '13:35', durationMin: 15, transitionRisk: 'caution', label: '🚶 15 min transition — tight against session start' },
  { type: 'session', time: '13:50', session: sessions[2] },
  { type: 'transition', time: '14:50', durationMin: 20, transitionRisk: 'go', label: '🚶 20 min transition to Venetian' },
  { type: 'session', time: '15:30', session: sessions[3] },
];

export const rerouteOptions: RerouteOption[] = [
  {
    id: 'opt-a',
    title: 'Swap to the 2:50 PM Observability Breakout',
    reason: 'Your original 1:50 PM session was moved to a venue 22 minutes away, which conflicts with your next booking.',
    impact: '+6% Journey Score, keeps your Observability path on track',
    sessions: ['ses-1003'],
    recommended: true,
  },
  {
    id: 'opt-b',
    title: 'Keep original session, accept a late arrival',
    reason: 'You would arrive roughly 9 minutes into the session.',
    impact: '+2% Journey Score, higher route risk',
    sessions: ['ses-1003'],
  },
  {
    id: 'opt-c',
    title: 'Skip this slot, use it as recovery time',
    reason: 'No suitable alternative closes the same gap in this time window.',
    impact: '0% Journey Score change',
    sessions: [],
  },
];

export const agentActivity: AgentActivityItem[] = [
  { id: 'act-1', timestamp: '09:58 AM', actor: 'agent', action: 'Detected route risk', detail: 'Walking time to Caesars Forum increased to 22 min due to a reported shuttle delay.', status: 'caution' },
  { id: 'act-2', timestamp: '09:58 AM', actor: 'agent', action: 'Generated 3 reroute options', detail: 'Ranked by journey impact and route risk.', status: 'info' },
  { id: 'act-3', timestamp: '10:01 AM', actor: 'user', action: 'Approved reroute', detail: 'Selected "Swap to the 2:50 PM Observability Breakout".', status: 'go' },
  { id: 'act-4', timestamp: '10:01 AM', actor: 'agent', action: 'Updated schedule', detail: 'Journey Score recalculated: 86% → 90%.', status: 'go' },
  { id: 'act-5', timestamp: 'Yesterday, 4:12 PM', actor: 'agent', action: 'Flagged missed session', detail: 'Cost-Aware Architecture session ended without check-in.', status: 'critical' },
];

export const journeyLog: JourneyLogEntry[] = [
  { id: 'jl-1', day: 'MON NOV 30', time: '09:00', type: 'attended', title: 'Building Production-Grade Agentic Workflows', detail: 'Checked in on time' },
  { id: 'jl-2', day: 'MON NOV 30', time: '10:01', type: 'rerouted', title: 'Route changed for Observability breakout', detail: 'Approved by you' },
  { id: 'jl-3', day: 'MON NOV 30', time: '11:00', type: 'attended', title: 'Threat Modeling for Autonomous AI Agents' },
  { id: 'jl-4', day: 'SUN NOV 29', time: '16:40', type: 'missed', title: 'Cost-Aware Architecture for Generative AI', detail: 'No check-in recorded' },
  { id: 'jl-5', day: 'SUN NOV 29', time: '09:00', type: 'milestone', title: 'Agentic AI category reached 100%' },
];

export const missionGoal = 'Become production-ready at building AI agents on AWS.';
